### ISSUE TITLE
Ignore Files

### ISSUE THREAD

**Issue by TransmissionsDev** [shogo82148/actions-goveralls#103]
Hey Shogo! 

This action is awesome, except I would really like to be able to ignore files from coverage reports. 

Turns out goveralls actually has support for this, and it would be awesome if you could allow users to pass down files to ignore using the `-ignore` flag in goveralls.

See details here:
https://github.com/mattn/goveralls/blob/f6a50649a3849a026ac29cd16b9bdfad0e46424d/goveralls.go#L65

**Comment by TransmissionsDev** [comment]
@shogo82148 Willing to make PR if you are willing to release it 😄

**Comment by shogo82148** [comment]
Thanks for your request!
I just published v1.3.0 that supports the `-ignore` flag.

**Comment by TransmissionsDev** [comment]
@shogo82148 Holy cow thats the fastest I've ever seen someone respond to a feature request and release it! Have a great day and thanks for maintaining this awesome action!
