### ISSUE TITLE
"Couldn't find a repository matching this job" after v1.3.0 release

### ISSUE THREAD

**Issue by arkn98** [shogo82148/actions-goveralls#107]
I think something broke after the `v1.3.0` release. I'm getting the message
```json
{
    "message": "Couldn't find a repository matching this job.",
    "error": true
}
```
after this update.

Link to a job that ran [today](https://github.com/arkn98/adeia-api/runs/700411890?check_suite_focus=true#step:5:13).
Link to a job that ran [yesterday](https://github.com/arkn98/adeia-api/runs/697289407?check_suite_focus=true#step:5:13) with the exact same workflow [file](https://github.com/arkn98/adeia-api/blob/feature-server/.github/workflows/test.yaml#L35-L56) and other relevant account settings (I mean, I didn't change any of my GitHub and Coveralls settings).

I don't know if I've done something wrong somewhere. Thanks in advance :)

**Comment by arkn98** [comment]
Does the action require `GITHUB-TOKEN` secret to be set?

I had builds succeed over the past month without setting any secret.

**Comment by shogo82148** [comment]
> Does the action require GITHUB-TOKEN secret to be set?
No, GitHub sets it automatically.

GitHub had some problems on that time, so please try it later

ref. https://www.githubstatus.com/incidents/6tcfpztf6j9m

> Update - We have identified the source causing elevated errors as well as occasional stale data on GitHub.com. We are working on remediation.
> May 22, 18:01 UTC
> Update - We continue to investigate an increase in errors on GitHub.com.
> May 22, 17:16 UTC

**Comment by arkn98** [comment]
It works now. Sorry for the inconvenience.
