### ISSUE TITLE
Coverage decreased when migrating from Travis

### ISSUE THREAD

**Issue by hhrutter** [shogo82148/actions-goveralls#178]
Hi!

First of all many thanks for all your hard work!!

I am in the process of migrating from TravisCI to Github Actions.
I followed your sample but I am getting a decreased coverage for some reason.

My tests are located in a special test package under api and cli respectively.
Looks like when running tests under api/test or cli/test coverage for statements outside those packages is not produced.

Here are the outputs from Github and Travis.
Travis does not show much but I added the urls to the corresponding Coveralls webpages which show the different results.
(Right now in a test branch pushing to Github triggers CI both Travis and GHActions)

Do you have any idea what's going here?

Github Actions:
```
Run go test -coverprofile=profile.cov ./...
...
ok  	github.com/pdfcpu/pdfcpu/pkg/api	0.016s	coverage: 0.3% of statements [no tests to run]
ok  	github.com/pdfcpu/pdfcpu/pkg/api/test	81.235s	coverage: [no statements]
...
```
Coveralls: https://coveralls.io/builds/36045053

TravisCI:
```
$ $HOME/gopath/bin/goveralls -service=travis-ci
Job #404.1
https://coveralls.io/jobs/72912922
The command "$HOME/gopath/bin/goveralls -service=travis-ci" exited with 0.
```
Coveralls: https://coveralls.io/builds/36045056

This is what I do locally to get the correct coverage results which corresponds to what I am getting using Travis:

```
rm $1

set -e

echo mode: set > $1

function internalDeps {

    for p in $(go list -f '{{.Deps}}' $1)
    do
        if [[ $p == github.com/pdfcpu/pdfcpu* ]]; then
            idep=$idep,$p 
        fi
    done
}

echo collecting coverage ...

for q in $(go list ./...)
do
    #echo collecting coverage for $q
    idep=$q
    internalDeps $idep
    if [[ $q == */test ]]; then
        idep=${idep%/test}
    fi
    go test -coverprofile=c.tmp -coverpkg=$idep $q && tail -n +2 c.tmp  >> $1
done

rm c.tmp

go tool cover -html=c.out
```

```
Go->  ./htmlcoverage.sh
collecting coverage ...
...
ok  	github.com/pdfcpu/pdfcpu/pkg/api	0.055s	coverage: 0.1% of statements in github.com/pdfcpu/pdfcpu/pkg/api, github.com/pdfcpu/pdfcpu/internal/config, github.com/pdfcpu/pdfcpu/internal/corefont/metrics, github.com/pdfcpu/pdfcpu/pkg/filter, github.com/pdfcpu/pdfcpu/pkg/font, github.com/pdfcpu/pdfcpu/pkg/log, github.com/pdfcpu/pdfcpu/pkg/pdfcpu, github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate, github.com/pdfcpu/pdfcpu/pkg/types [no tests to run]
ok  	github.com/pdfcpu/pdfcpu/pkg/api/test	55.352s	coverage: 71.1% of statements in github.com/pdfcpu/pdfcpu/pkg/api
...
```

**Comment by shogo82148** [comment]
remove `path-to-profile` and run it again please.

```yaml
- uses: actions/checkout@v2
# - run: go test -coverprofile=profile.cov ./...
- uses: shogo82148/actions-goveralls@v1
#  with:
#    path-to-profile: profile.cov
```

it is same as running `goveralls -service=github`, so you will get same result.

**Comment by hhrutter** [comment]
Thanks, it's now working for *ubuntu-latest* 👍 

When using *macos-latest* I get [the following error](https://github.com/pdfcpu/pdfcpu/actions/runs/462039735). This is strange because it works on Travis:
```
/Users/runner/work/_actions/shogo82148/actions-goveralls/v1/bin/goveralls_darwin_amd64 -coverprofile= -service=github -ignore= -parallel -flagname=Go-
22:00:02 gocover.go:111: Can't find can't find "metrics.go": go/build: go list github.com/pdfcpu/pdfcpu/internal/corefont/metrics/: exit status 2
go: cannot find GOROOT directory: /usr/local/go

Error: The process '/Users/runner/work/_actions/shogo82148/actions-goveralls/v1/bin/goveralls_darwin_amd64' failed with exit code 1
```

Also are you also supporting pipelines using different architectures?
Your example only show an ubuntu matrix over different Go versions. 

Thanks so much for your help!

**Comment by shogo82148** [comment]
🤔 
The action also supports macOS and Windows.
I'll check it.

**Comment by hhrutter** [comment]
It's working now on *macos-latest* and *ubuntu-latest*.
Don't ask me why 🤷‍♂️ maybe my yml was bad.
Thanks again for your time 👍
