### ISSUE TITLE
Coverage decreased (-0.0%) make status is error

### ISSUE THREAD

**Issue by mozillazg** [shogo82148/actions-goveralls#186]
First of all, thanks for your work. This project is so awesome!

I am not sure the `Coverage decreased (-0.0%)` issue is caused by actions-goveralls or coveralls, Do you have any idea? Thanks!

<img width="403" alt="image" src="https://user-images.githubusercontent.com/485054/105618854-f78e5300-5e26-11eb-8585-d63df83f552f.png">

The yaml file is here: https://github.com/mozillazg/go-httpheader/blob/master/.github/workflows/main.yml

**Comment by shogo82148** [comment]
The configures of the GitHub status are on https://coveralls.io/ , not in YAML files.

At first, visit https://coveralls.io/github/:owner/:repo/settings or click the "setting" link on your project page.
<img width="1440" alt="settings" src="https://user-images.githubusercontent.com/1157344/105645970-7a271900-5ee0-11eb-8cbc-1fb8d131950a.png">

You will find the "PULL REQUESTS ALERTS" section, and can configure thresholds here.
<img width="1440" alt="settings" src="https://user-images.githubusercontent.com/1157344/105645963-75fafb80-5ee0-11eb-869c-0f98cd12a3f0.png">

**Comment by mozillazg** [comment]
@shogo82148 After changed the settings on coveralls.io my issue is resolved. Thanks for your help!
