### ISSUE TITLE
`cannot import absolute path` error

### ISSUE THREAD

**Issue by EgorKorol** [shogo82148/actions-goveralls#193]
Hi @shogo82148 !
I am a new one in go and GitHub actions and I have just tried to connect coveralls to my test repository for coverage shows. But I can not finish it with your action and I do not have any ideas why :)  Could you please help me?

This is the link to my pipeline https://github.com/EgorKorol/test-coverage/pull/7/checks?check_run_id=1935799524

**Comment by shogo82148** [comment]
GOPATH mode doesn't work correctly because actions/checkout doesn't know about it.
I recommend you to enable module-aware mode.

https://github.com/golang/go/wiki/Modules

**Comment by EgorKorol** [comment]
Yes, it works! Thank you!
