### ISSUE TITLE
State of this project compared to `mattn/goveralls`

### ISSUE THREAD

**Issue by jderusse** [shogo82148/actions-goveralls#39]
You are the maintainer of both project `shogo82148/actions-goveralls` and `mattn/goveralls` (thank for your work !!).
If I understand correctly, both does the same thing, which project should I use? What's your recommendation?

Shouldn't we deprecated one project in favor of the other?

**Comment by shogo82148** [comment]
If you use with GitHub Actions, I recommend `shogo82148/actions-goveralls`.
Or if you use with other CI services, you can continue to use `mattn/goveralls`.

`shogo82148/actions-goveralls` just provides the shorthand of the GitHub Actions YAML configure and pre-built binaries.
It depends on `mattn/goveralls` for most feature.
So, I will not deprecate any project.

**Comment by jderusse** [comment]
thank for the pointer.
